### PR TITLE
Autocomplete for EU Vote Task

### PR DESCRIPTION
**Pull request by jsanko9**
Adding some autocomplete/auto-fill properties

- Municipality was drop-down object thus could not autocomplete.
- Personal ID and Nationality are out of scope of autocomplete.

Even with this being a partial solution, my biggest problem was to enter address with correct diacritic on my US English only device, this solves that for me.

### CODE REVIEW

**Comment by jsanko9** [comment]
wow,
vypada ze som spravil kopiu:  #161 
- street address je ale multiline a municipality je UI komponent dropdown, takze moja verzia je (asi) lepsia. Tiez pozeram na Ruby prvy krat.

**Comment by jsuchal** [comment]
Ano je to mozne, ze si vyrobil trochu kopiu, v kazdom pripade kedze deadline bol piatok je to uz trochu irrelevatne :) Ten predchadzajuci som nemergoval lebo som to lokalne nejako nevedel ani vyskusat ci to ide. Skusim toto tvoje.

**Comment by jsanko9** [comment]
> Ano je to mozne, ze si vyrobil trochu kopiu, v kazdom pripade kedze deadline bol piatok je to uz trochu irrelevatne :) Ten predchadzajuci som nemergoval lebo som to lokalne nejako nevedel ani vyskusat ci to ide. Skusim toto tvoje.

Aj jeho by ti malo ist, ak si to nezapol automaticky v chrome to je tu:
chrome://settings/addresses

Inac neviem ako ty, ale toto nie su pre mna posledne EP volby, dufam.

**Comment by jsuchal** [comment]
Hej jasne, tak som to nemyslel, ze to je nanic, sorry. Poskusam a mergnem. Diky. Inak na http://slack.slovensko.digital si?

**Comment by jsanko9** [comment]
Som tam od Piatka. Dik za invite.

**Pull request merged**
